### ISSUE TITLE
Really want to use it, but it's not working!

### ISSUE THREAD

**Issue by ohheyyeahthatsme** [novemberfiveco/symbol-spacer-sketch-plugin#2]
I downloaded & double-clicked, it didn't seem to work. I also tried installing through Sketch Toolbox, nada! It's definitely installed, I see it in my Plugins folder, and I doubled checked my naming convention, but yeah, not working for me sadly.

**Comment by GeertWille** [comment]
Did you download from [release](https://github.com/novemberfiveco/symbol-spacer-sketch-plugin/releases/tag/v0.1.0)?

**Comment by ohheyyeahthatsme** [comment]
Perfect, replaced it and it works now, thanks!

**Comment by kylamedina** [comment]
@GeertWille maybe you should mention that in the readme

**Comment by kylamedina** [comment]
or it would be great if it was in Sketch Runner

**Comment by GeertWille** [comment]
@kylamedina it states that in the readme 😃  Anyway I'll look into it to make it work with sketch runner etc...

**Comment by kylamedina** [comment]
I realize it does but there's also a giant download button at the top that plebes like me assume does the same thing because normally it does.

**Comment by GeertWille** [comment]
It's because the project is made to be changed by other developers and also supports the new automatic update system of sketch 46 which requires me to add in extra files. If you now download it as a zip you get all this stuff you don't need. That's why I now use the release part of Github. Anyways I'll try to fix it for the non-developers so they can easily install it with sketch runner.
